### PR TITLE
Added CSV resource files

### PR DESCRIPTION
**Pull request by Pete1001**
Pull request to pull new changes

### CODE REVIEW

**Review by steve-vierling — APPROVED** [review]
Changes look good to me

**Review by ewyman87 — APPROVED** [review]
Data look good, approved

**Review by steve-vierling — CHANGES_REQUESTED** [review]
2nd attempt, I am now requesting changes

**Review by ewyman87 — APPROVED** [review]
Data look good

**Review by steve-vierling — APPROVED** [review]
As an official collaborator on this repo now, I approve this change.

**Pull request merged**
